#!/bin/sh
DAEMON="modprobe"

start() {
	printf "Starting $DAEMON: "
	modprobe rtlwifi && \
	modprobe rtl8192c_common && \
	modprobe rtl_usb && \
	modprobe rtl8192cu && \
	echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping $DAEMON: "
	echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
