#!/bin/sh
DAEMON="eeprom"

start() {
	printf "Starting $DAEMON: "
    modprobe i2c-dev && modprobe at24 && \
    echo "24c32 0x50" > /sys/class/i2c-dev/i2c-0/device/new_device \
    && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping $DAEMON: "
    rmmod at24 && echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
