#!/bin/sh
DAEMON="rtc"

start() {
	printf "Starting $DAEMON: "
    /root/ds1307_init.sh && /root/ds1307_get.sh \
		&& echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping $DAEMON: "
    /root/ds1307_put.sh \
		&& echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
