#!/bin/sh
DAEMON="rtc"

start() {
	printf "Starting $DAEMON: "
    modprobe i2c-dev && modprobe rtc-ds1307 &&
    echo ds1307 0x68 > /sys/class/i2c-dev/i2c-0/device/new_device && \
    hwclock -s -u -f /dev/rtc1 \
		&& echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping $DAEMON: "
    hwclock -w -u -f /dev/rtc1 && rmmod rtc-ds1307 \
		&& echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
