#!/bin/sh
DAEMON="pure-ftpd"
PIDFILE="/var/run/pure-ftpd.pid"
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

start() {
	# Change group and write permissions of anonymous FTP
	chgrp ftp /var/lib/mpd/music
	chmod g+w /var/lib/mpd/music
	printf "Starting pure-ftpd: "
	start-stop-daemon --start --quiet --background \
		--exec "/usr/sbin/pure-ftpd" -- /etc/pure-ftpd.conf \
		&& echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping pure-ftpd: "
	start-stop-daemon --stop --quiet -p $PIDFILE \
		&& echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
