#!/bin/sh
DAEMON="ympd"
HOST="localhost"
PORT=6600
# default is 8080
WEB_PORT=80
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

start() {
	printf "Starting ympd: "
	start-stop-daemon --start --quiet --background --exec "/usr/bin/ympd -h $HOST -p $PORT -w $WEB_PORT" \
		&& echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping ympd: "
	start-stop-daemon --stop --quiet --pidfile /var/run/ympd.pid \
		&& echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
